name: hdfs
version: 0.0.0
description: A package:file implementation that interacts with a Hadoop File System instance.
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_serialize: ^2.0.0
  file: ^5.0.0
  http: ^0.12.0
dev_dependencies:
  angel_framework: ^2.0.0
  angel_serialize_generator: ^2.0.0
  angel_static: ^2.0.0
  build_runner: ^1.0.0
  pedantic: ^1.0.0
  pretty_logging: ^1.0.0
  test: ^1.0.0
